spring.application.name=backend
spring.config.import=optional:file:backend-java/.env[.properties]
# CONFIGURACIÓN DEL SERVIDOR
server.port=${PORT:8080}

# PERSISTENCIA SQL (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/ia_chatbot
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# PERSISTENCIA NOSQL (MongoDB - RAG)
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/tu_bd_rag}

# INTEGRACIÓN CON PYTHON (Variables personalizadas para tu Service)
python.executable=${PYTHON_EXECUTABLE:python}
python.script.path=${PYTHON_SCRIPT_PATH:../backend-python/chatbot-mejorado.py}

# CONFIGURACIÓN AZURE OPENAI (Disponibles para inyectar con @Value)
azure.openai.api-key=${API_KEY}
azure.openai.deployment-name=${DEPLOYMENT_NAME}
azure.openai.endpoint=${API_EXTERN_MAIN_ENDPOINT}
azure.openai.api-version=${AZURE_OPENAI_API_VERSION}